[project]
name = "ecommerce-suite-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anurag180259", email = "anuragninawe1802@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=2.2.0",
]

[project.scripts]
ecommerce-suite-mcp-server = "ecommerce_suite_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
